services:
  python:
    container_name: nebula_discord_bot
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11.4-alpine3.18
        WORKDIR /home
        RUN pip install -r ./requirements.txt
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - ./requirements.txt:/home/requirements.txt
      - ./app:/home/app
    command: python app/main.py